### ISSUE TITLE
Recursive dynamic completer?

### ISSUE THREAD

**Issue by nights99** [chzyer/readline#115]
Is it possible for dynamic completers to be called 'recursively' to build up a path?

To clarify by referring to listFiles() in the example code - if the first listFiles() returned a directory, could it indicate it should be called again with the chosen completion as the input, so that it could then list files in that directory, and so on, until a complete path was formed?

**Comment by lmorg** [comment]
I'm in a similar situation as I'm using this package for a REPL shell I'm building and the only way I've found to chain dynamic completers recursively caused no end of bugs. But pragmatically I think what I really need is more along the lines of a dynamic mid-line completer rather than a nested prefix completer since each prefix is dynamic.

**Comment by lmorg** [comment]
Is there any update on this?

This project does tick quite a few boxes for me by the aforementioned issue is a deal breaker. I appreciate this is open source and likely maintained as a hobby, but the lack of documentation and the overly complex APIs to create dynamic prefix completions mean I've wasted a lot of my own time trying to integrate this into my own project. So I'm wondering where I go from here. If this project still maintained? Is what I'm trying to do even possible with this project?

**Comment by lmorg** [comment]
@nights99 

I finally cracked the recursive completer. The trick is not to use the dynamic completer but instead create your own `readline.AutoCompleter` interface{}. I'm throwing some code online later today if you are still interested in solving your problem?

I'm really grateful for the author of this package and appreciate documentation can be boring but it would have gone a long way if s/he had even just responded to Github issues guiding people in the right direction.

**Comment by nights99** [comment]
@lmorg 

I had put this to one side, but if you have a solution, I'm definitely still interested in looking at this again - thanks!

**Comment by lmorg** [comment]
@nights99 

You need to create your own completer:

```
type ExampleCompleter struct{}

var exampleCompleter *ExampleCompleter = new(ExampleCompleter)

func (mc ExampleCompleter) Do(line []rune, pos int) (suggest [][]rune, retPos int) {
        // do stuff
}

func main() {
	Instance, err = readline.NewEx(&readline.Config{
		AutoComplete: exampleCompleter,
	})
}
// ...
```
The retPos is important as that's where you can set the partial completions (eg you type `exam[tab]` and you get `example`). If you don't set the retPos correctly the autocomplete will append `example` to the end of your line (eg `examexample`).

It's a bit fiddly and I found I needed a bit of trial and error to get it working but once you get over the initial hurdles it because quite quick to add items.

The project I was working on utilising this is open source so feel free to copy my implementation or just use it as reference:

Completer: https://github.com/lmorg/murex/blob/master/shell/parser.go
Readline config: https://github.com/lmorg/murex/blob/master/shell/shell.go

**Comment by nights99** [comment]
@lmorg 
Brilliant, thanks. It'll be a little while before I'll have chance to try it out, but looks like there's plenty of info there to let me get things working. Thanks for all the help.
