### ISSUE TITLE
Read from /dev/tty instead of stdin

### ISSUE THREAD

**Issue by edi9999** [chzyer/readline#57]
I would like to create a program in the same spirit as [fzf](https://github.com/junegunn/fzf)

I would like to use stdin myself in myprogram

cat /etc/var/nginx.log | myprogram

And be able to use readline inside my program.

Here's how fzf does it : 

https://github.com/junegunn/fzf/blob/c62fc5e75c09262a384e703800fefa6850afa2e8/src/curses/curses.go#L287

Do you think it is possible ?

**Comment by chzyer** [comment]
You can set `*Config.Stdin` as whatever you want.

If you want readline run in non-tty environment, functions as follow needs to be rewrite.
```
FuncGetWidth       func() int
FuncIsTerminal     func() bool
FuncMakeRaw        func() error
FuncExitRaw        func() error
FuncOnWidthChanged func(func())
```

[`remote.go`](https://github.com/chzyer/readline/blob/master/remote.go) also supports using local tty connect to remote readline, so I think read from /dev/tty instead of stdin is not a problem.
